import streamlit as st

st.set_page_config(page_title="Privacy Policy - GenomEA", page_icon="🔒")

st.title("Privacy Policy 🔒")
st.write("Last updated: May 2026")
st.divider()

st.write("""
GenomEA collects only the minimum information necessary to provide its services. 
By using GenomEA, you agree to the terms outlined in this policy.
""")

st.header("1. Information We Collect")
st.write("GenomEA collects only the minimum information necessary to provide its services, biological sequence data submitted for analysis, uploaded files in FASTA, GenBank or other supported formats, analysis preferences and settings selected during a session and basic usage data such as analysis type and timestamp, which is collected for service improvement")
st.write("GenomEA does not collect personal identifiers such as name, national ID or physical address unless voluntarily provided through the contact form.")

st.header("2. How We Use Your Information")
st.write("Information is used exclusively for running analysis, generating AI summaries and improving the platform. We do not sell or share your data. By using GenomEA, you acknowledge that your sequence data may be transmitted to these services for the sole purpose of analysis.")

st.header("3. Research Disclaimer")
st.error("Results generated by GenomEA are intended for research purposes only. GenomEA outputs should not be used for clinical diagnosis, medical decision-making or patient care without independent validation by a qualified professional. GenomEA accepts no liability for decisions made based on its outputs.")

st.header("4. Contact")
st.write("For questions contact: bryson6742@gmail.com")